// THIS FILE IS GENERATED BY PYRIN ZOD CODE GENERATOR
import { z } from "zod";

export const Artist = z.object({
  id: z.string(),
  name: z.string(),
  picture: z.string(),
});
export type Artist = z.infer<typeof Artist>;

export const Album = z.object({
  id: z.string(),
  name: z.string(),
  coverArt: z.string(),
  artistId: z.string(),
});
export type Album = z.infer<typeof Album>;

export const Track = z.object({
  id: z.string(),
  number: z.number(),
  name: z.string(),
  coverArt: z.string(),
  duration: z.number(),
  bestQualityFile: z.string(),
  mobileQualityFile: z.string(),
  albumId: z.string(),
  artistId: z.string(),
  albumName: z.string(),
  artistName: z.string(),
});
export type Track = z.infer<typeof Track>;

export const Tag = z.object({
  id: z.string(),
  name: z.string(),
});
export type Tag = z.infer<typeof Tag>;

export const Playlist = z.object({
  id: z.string(),
  name: z.string(),
});
export type Playlist = z.infer<typeof Playlist>;

export const GetArtists = z.object({
  artists: z.array(Artist),
});
export type GetArtists = z.infer<typeof GetArtists>;

export const GetArtistById = Artist;
export type GetArtistById = z.infer<typeof GetArtistById>;

export const GetArtistAlbumsById = z.object({
  albums: z.array(Album),
});
export type GetArtistAlbumsById = z.infer<typeof GetArtistAlbumsById>;

export const GetAlbums = z.object({
  albums: z.array(Album),
});
export type GetAlbums = z.infer<typeof GetAlbums>;

export const GetAlbumById = Album;
export type GetAlbumById = z.infer<typeof GetAlbumById>;

export const GetAlbumTracksById = z.object({
  tracks: z.array(Track),
});
export type GetAlbumTracksById = z.infer<typeof GetAlbumTracksById>;

export const GetTracks = z.object({
  tracks: z.array(Track),
});
export type GetTracks = z.infer<typeof GetTracks>;

export const GetTrackById = Track;
export type GetTrackById = z.infer<typeof GetTrackById>;

export const GetSync = z.object({
  isSyncing: z.boolean(),
});
export type GetSync = z.infer<typeof GetSync>;

export const PostQueue = z.object({
  tracks: z.array(Track),
});
export type PostQueue = z.infer<typeof PostQueue>;

export const GetTags = z.object({
  tags: z.array(Tag),
});
export type GetTags = z.infer<typeof GetTags>;

export const PostAuthSignupBody = z.object({
  username: z.string(),
  password: z.string(),
  passwordConfirm: z.string(),
});
export type PostAuthSignupBody = z.infer<typeof PostAuthSignupBody>;

export const PostAuthSignup = z.object({
  id: z.string(),
  username: z.string(),
});
export type PostAuthSignup = z.infer<typeof PostAuthSignup>;

export const PostAuthSigninBody = z.object({
  username: z.string(),
  password: z.string(),
});
export type PostAuthSigninBody = z.infer<typeof PostAuthSigninBody>;

export const PostAuthSignin = z.object({
  token: z.string(),
});
export type PostAuthSignin = z.infer<typeof PostAuthSignin>;

export const GetAuthMe = z.object({
  id: z.string(),
  username: z.string(),
});
export type GetAuthMe = z.infer<typeof GetAuthMe>;

export const PostPlaylistBody = z.object({
  name: z.string(),
});
export type PostPlaylistBody = z.infer<typeof PostPlaylistBody>;

export const PostPlaylistItemsByIdBody = z.object({
  tracks: z.array(z.string()),
});
export type PostPlaylistItemsByIdBody = z.infer<typeof PostPlaylistItemsByIdBody>;

export const GetPlaylistById = z.object({
  id: z.string(),
  name: z.string(),
  items: z.array(Track),
});
export type GetPlaylistById = z.infer<typeof GetPlaylistById>;

export const GetPlaylists = z.object({
  playlists: z.array(Playlist),
});
export type GetPlaylists = z.infer<typeof GetPlaylists>;

