// THIS FILE IS GENERATED BY PYRIN JSGEN CODE GENERATOR
import { z } from "zod";

export const Artist = z.object({
  id: z.string(),
  name: z.string(),
  picture: z.string(),
});
export type Artist = z.infer<typeof Artist>;

export const Album = z.object({
  id: z.string(),
  name: z.string(),
  coverArt: z.string(),
  artistId: z.string(),
});
export type Album = z.infer<typeof Album>;

export const Track = z.object({
  id: z.string(),
  number: z.number(),
  name: z.string(),
  coverArt: z.string(),
  duration: z.number(),
  bestQualityFile: z.string(),
  mobileQualityFile: z.string(),
  albumId: z.string(),
  artistId: z.string(),
  albumName: z.string(),
  artistName: z.string(),
});
export type Track = z.infer<typeof Track>;

export const GetArtists = z.object({
  artists: z.array(Artist),
});
export type GetArtists = z.infer<typeof GetArtists>;

export const GetArtistById = Artist;
export type GetArtistById = z.infer<typeof GetArtistById>;

export const GetArtistAlbumsById = z.object({
  albums: z.array(Album),
});
export type GetArtistAlbumsById = z.infer<typeof GetArtistAlbumsById>;

export const GetAlbums = z.object({
  albums: z.array(Album),
});
export type GetAlbums = z.infer<typeof GetAlbums>;

export const GetAlbumById = Album;
export type GetAlbumById = z.infer<typeof GetAlbumById>;

export const GetAlbumTracksById = z.object({
  tracks: z.array(Track),
});
export type GetAlbumTracksById = z.infer<typeof GetAlbumTracksById>;

export const GetTracks = z.object({
  tracks: z.array(Track),
});
export type GetTracks = z.infer<typeof GetTracks>;

export const GetTrackById = Track;
export type GetTrackById = z.infer<typeof GetTrackById>;

export const GetSync = z.object({
  isSyncing: z.boolean(),
});
export type GetSync = z.infer<typeof GetSync>;

